### ISSUE TITLE
Content Review

### ISSUE THREAD

**Issue by adelnehme** [ramnathv/live-webinar-shiny#1]
Hi @ramnathv :wave:

Here's my review of the content on the RStudio Cloud version. I'm assuming the folder `notes` contains all the relevant `.RMD` files and will be reviewing them here.

### 2.1- Inputs

- [x] 🔍  **1.** Is there any specific reason why we introduce we define an empty server function at the beginning? I'm actually a fan of repeatedly defining an empty server function for each input we are showcasing since it reinforces the idea that reactivity is in the `server()` function - whereas the front end is in the `ui` function. For example, the file would kind of look like this:

```{r setup, include = FALSE}
# Load shiny
library(shiny)
# Load tidyverse
library(tidyverse)

if (requireNamespace('rstudioapi', quietly = TRUE)){
  options(shiny.launch.browser = rstudioapi::viewer)
}
```

`## Shiny 101`

```{r}
ui <- fluidPage(
  # 1. Add a text input to get user name
  textInput('name', label = 'Enter your name'),
  # 3. Display text output with greeting
  textOutput('greeting')
)
server <- function(input, output, session){
  # 2. Render a text greeting
  output$greeting <- renderText({
    paste("Hello,", input$name)
  })
}

shinyApp(ui, server)
```

`## Text`

`### textInput`

```{r}
ui <- fluidPage(
  # Add a text input to get name
  textInput(
    inputId = 'name',
    label = 'Enter your name'
  )
)

# Define empty server function
server <- function(input, output, session) {

}

shinyApp(ui, server)
```

`### textAreaInput`

```{r}
ui <- fluidPage(
  # Add a text area input to get user feedback
  textAreaInput(
    inputId = 'feedback', 
    label = 'Add your feedback'
  )
)

# Define empty server function
server <- function(input, output, session) {

}

shinyApp(ui, server)
```

- [x] 🤔  **2.** I see there are sections for "CheckboxInput" - "checkboxGroupInput" - "varSelectInput" - "numericInput" - "sliderInput" and "DateInput" - "DateRangeInput" - "radioButtons" - "checkboxInput" - "reactivity". Are you going to be covering all of these sections in this file? Including reactivity? Isn't that for the second file for outputs?

- [x] 🔧 **3.** I see in the 2.2- outputs file we immediately go into plotting and datatables - I recommend showcasing at the end of this file at least that these inputs exist to connect it easily to 2.2.

### 2.2-outputs

- [x] 🔧 **3.** I think given **1** and the definition of an empty server function each time we introduce a new input - I recommend having at least a few examples from `2.1` with filled out UI and an empty server function that you populate to showcase reactivity. This creates narrative and lets you connect back the input and output files. 

- [x] 🔧 **4.** DTOutput returns a "no package named DT" error.

- [x] 🔧 **5.** Plotlyoutput returns "no package called plotly"

### 2.3-layouts

- [x] 🔧 **6.** There is no package called "shinythemes"

- [x] 🔧 **7.** I think it's worth showcasing an example where you introduce reactivity between one UI element and the server function inside of a tab panel somewhere to showcase how it works 😄 

### 2.4-moma

- [x] 🔧 **8.** This code snippet here returns an error no package called janitor

```
artists <- readr::read_csv('../data/Artists.csv') %>% 
  janitor::clean_names()
artists
```

**Comment by ramnathv** [comment]
Thanks @adelnehme. I have incorporated all the feedback provided here.
