### ISSUE TITLE
Feedback on Notebook

### ISSUE THREAD

**Issue by adelnehme** [ramnathv/live-webinar-shiny#2]
Hi @ramnathv :wave:

Here's some last-minute feedback for the notebooks - make sure to apply these changes in both solution and session RMD files.

- [x] 🤔  **1.** I see that in the student notebook you do not have the `DyGraphs` section in blank - are you just showcasing it here as an example of functionality shiny has without necessarily teaching it? I think that would be ideal to reduce the variety and cognitive overload. 

- [x] 🔧 **2.** Add a Q&A session after the output section

- [x] 🔧 **3.** There seems to be misalignment between student code and solution code in Reactivity 101 wherein the session notebook students are being told to copy the code of the app they created even though they didn't create a Baby Names Explorer app. 

![image](https://user-images.githubusercontent.com/48436758/85694652-9a3af380-b6d7-11ea-8d37-3e9c05eddc02.png)

---

![image](https://user-images.githubusercontent.com/48436758/85694694-a58e1f00-b6d7-11ea-8f34-08d77806891b.png)

- [x] 🤔 **4.** Going on the solution code - the objective of this section is to create a barebones baby names explorer with easy reactivity and adding more and more functionality to it. This requires students to write a baby names app from line 349 to 362 and copy-pasting it to another cell to add more functionality and so on and so forth. One thing I'm worried about here is that students may get confused or lost while copy-pasting. There are 2 ways to alleviate this - **1st solution** is on the speaker side and making sure you are cognizant of this risk while teaching this section (meaning we'd have to be extra attentive to naming code lines "Now we're copy-pasting this section here on line 349 to the next section to add more functionality" and doing things slowly and patiently) - or **the second solution** is leave the code in 349 empty and fill that out - but all subsequent code cells where we add more functionality to the app will have the barebones version of the app that we will add functionality to. 

- [x] 🔧 **5.** On line 533 and 570 we are also requiring students to copy-paste the app they created earlier and adjusting the code slightly to have layouts - I recommend instead having the code for the baby names app in these 2 code cells and we would just adjust the layout there - eliminating the copy-paste step only.  

- [x] 🔧 **6.** Can we have a clearer distinction between sections? For example having I) Inputs and having a line separator between different sections `=========================================================================`

**Comment by ramnathv** [comment]
@adelnehme Thanks for all the feedback. It was super useful!!! I addressed all the feedback. On the issue of Copy-Paste, I have reduced the amount of Copy-Paste required. Eliminating copy-paste completely makes the code chunks clunky. I will make sure I keep it slow with the copy-paste.
